POST http://localhost:4002/reports
content-type: application/json

{
  "make": "Honda",
  "model": "City",
  "year": 2018,
  "mileage": 100000,
  "lng": 80.2350,
  "lat": 13.0827,
  "price": 1000000
}